//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.12.08 at 05:06:39 PM IST 
//


package com.infosys.spring_boot_soap_example_address;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.infosys.spring_boot_soap_example_address package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.infosys.spring_boot_soap_example_address
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link UpdateAddressRequest }
     * 
     */
    public UpdateAddressRequest createUpdateAddressRequest() {
        return new UpdateAddressRequest();
    }

    /**
     * Create an instance of {@link Address }
     * 
     */
    public Address createAddress() {
        return new Address();
    }

    /**
     * Create an instance of {@link AddAddressRequest }
     * 
     */
    public AddAddressRequest createAddAddressRequest() {
        return new AddAddressRequest();
    }

    /**
     * Create an instance of {@link AddAddressResponse }
     * 
     */
    public AddAddressResponse createAddAddressResponse() {
        return new AddAddressResponse();
    }

    /**
     * Create an instance of {@link ServiceStatus }
     * 
     */
    public ServiceStatus createServiceStatus() {
        return new ServiceStatus();
    }

    /**
     * Create an instance of {@link DeleteAddressResponse }
     * 
     */
    public DeleteAddressResponse createDeleteAddressResponse() {
        return new DeleteAddressResponse();
    }

    /**
     * Create an instance of {@link GetAddressRequest }
     * 
     */
    public GetAddressRequest createGetAddressRequest() {
        return new GetAddressRequest();
    }

    /**
     * Create an instance of {@link GetAddressResponse }
     * 
     */
    public GetAddressResponse createGetAddressResponse() {
        return new GetAddressResponse();
    }

    /**
     * Create an instance of {@link UpdateAddressResponse }
     * 
     */
    public UpdateAddressResponse createUpdateAddressResponse() {
        return new UpdateAddressResponse();
    }

    /**
     * Create an instance of {@link GetAddressByIdRequest }
     * 
     */
    public GetAddressByIdRequest createGetAddressByIdRequest() {
        return new GetAddressByIdRequest();
    }

    /**
     * Create an instance of {@link DeleteAddressRequest }
     * 
     */
    public DeleteAddressRequest createDeleteAddressRequest() {
        return new DeleteAddressRequest();
    }

    /**
     * Create an instance of {@link GetAddressByIdResponse }
     * 
     */
    public GetAddressByIdResponse createGetAddressByIdResponse() {
        return new GetAddressByIdResponse();
    }

}
