//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.12.08 at 05:06:39 PM IST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://infosys.com/spring-boot-soap-example-address", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.infosys.spring_boot_soap_example_address;
